name: Update Protomaps

on:
  workflow_dispatch:

jobs:
  update-tiles:
    runs-on: 
      labels: ubuntu-latest
    
    steps:
      - name: Set AWS credentials
        env:
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
        run: |
          echo "Setting AWS Credentials"
          aws configure set aws_access_key_id "$R2_ACCESS_KEY_ID"
          aws configure set aws_secret_access_key "$R2_SECRET_ACCESS_KEY"
          aws configure set default.region auto

      - name: Download latest tileset
        run: |
          TODAY="$(date +'%Y%m%d')"
          echo "TODAY=$TODAY" >> $GITHUB_ENV
          echo "Today's date for filename is $TODAY"
          echo "Downloading protomaps pmtiles file."
          wget https://build.protomaps.com/"${TODAY}".pmtiles

      - name: Upload tileset to Cloudflare R2
        env:
          R2_API_ENDPOINT: ${{ secrets.R2_API_ENDPOINT }}
        run: |
          echo "Uploading file to Cloudflare R2"
          aws s3 cp "${{ env.TODAY }}".pmtiles s3://exploreearth/world.pmtiles --endpoint-url https://"$R2_API_ENDPOINT".r2.cloudflarestorage.com